Iter13
UsachevDmitry/mcaas pull request #13
Opened 2024-12-01 13:29 UTC by UsachevDmitry

2024-12-02 14:49 UTC, edylcrm requested changes

2024-12-02 14:49 UTC, edylcrm commented on internal/agent/data.go
> +var mutexForMetricsList sync.Mutex
Опять же лучше отдельной структурой без глобального мьютекса и переменной т.к. ее можно изменить везде и забыть про mutex.

2024-12-02 14:49 UTC, edylcrm commented on internal/agent/send_metrics.go
> +		for i := 1; i < 6; i += 2 {
С i == 5 и i == 6 выглядит не очень понятно. Можно ли здесь как-то переписать?

2024-12-02 14:49 UTC, edylcrm commented on internal/server/data.go
> +var DB *sql.DB
Тоже самое про глобальное состояние

2024-12-02 14:49 UTC, edylcrm commented on internal/server/data.go
> +		UpdateGaugeSQL(context.Background(), key, value)
А сделать две отдельные структуры? Одну для memstorage другую для БД, определить для них общий интерфейс и в зависимости от конфигурации приложения передавать разные имплементации?

2024-12-02 14:49 UTC, edylcrm commented on internal/server/db.go
> +			i = 6
Тоже не понятно зачем это и почему

2024-12-02 14:49 UTC, edylcrm commented on internal/server/db.go
> +			time.Sleep(time.Second * time.Duration(i))
На большом кол-ве запросов это приведет к деградации т.к. коннекты к бд будут заняты. Предлагаю слип полностью исключить

2024-12-02 15:59 UTC, UsachevDmitry commented on internal/agent/data.go
> +var mutexForMetricsList sync.Mutex
Поправил

2024-12-02 16:53 UTC, UsachevDmitry commented on internal/server/db.go
> +			i = 6
Поправил

2024-12-03 19:08 UTC, UsachevDmitry commented on internal/agent/send_metrics.go
> +		for i := 1; i < 6; i += 2 {
поправил

2024-12-03 19:08 UTC, UsachevDmitry commented on internal/server/db.go
> +			time.Sleep(time.Second * time.Duration(i))
поправил согласно договоренности после 1 to 1

2024-12-05 11:06 UTC, UsachevDmitry commented on internal/server/data.go
> +var DB *sql.DB
Поправил и заменил на

2024-12-05 11:07 UTC, UsachevDmitry commented on internal/server/data.go
> +		UpdateGaugeSQL(context.Background(), key, value)
Сделал

2024-12-05 11:08 UTC, UsachevDmitry commented on internal/server/data.go
> +		UpdateGaugeSQL(context.Background(), key, value)
Но не уверен что до конца. На следующей неделе хотел бы на 1to1 в понедельник еще раз обсудить.

2024-12-05 16:13 UTC, edylcrm approved these changes

2024-12-11 17:44 UTC, merged