Iter5
UsachevDmitry/mcaas pull request #5
Opened 2024-10-28 21:49 UTC by UsachevDmitry

iter5

2024-10-31 08:53 UTC, edylcrm requested changes

2024-10-31 08:53 UTC, edylcrm commented on cmd/agent/data.go
> +	MetricsGauge:   map[string]gauge{},
Здесь может быть race condition, лучше добавить mutex

2024-10-31 08:53 UTC, edylcrm commented on cmd/server/data.go
> +var Data = MemStorage{
Я бы все таки предложил всю бизнес логику вынести в internal, в пакете main оставил только инициализацию приложения

2024-11-01 14:32 UTC, edylcrm commented on cmd/server/handleIndex.go
> +		log.Fatalln(err)
Здесь вернуть http code с ошибкой

2024-11-05 20:22 UTC, UsachevDmitry commented on cmd/server/data.go
> +var Data = MemStorage{
fixed

2024-11-07 08:25 UTC, UsachevDmitry commented on cmd/agent/data.go
> +	MetricsGauge:   map[string]gauge{},
Добавлены mutex в каждую функцию записывающую в map'ы

2024-12-11 17:44 UTC, merged