Iter9
UsachevDmitry/mcaas pull request #9
Opened 2024-11-19 20:52 UTC by UsachevDmitry

iter9 in progress

2024-11-21 12:58 UTC, edylcrm requested changes

2024-11-21 12:58 UTC, edylcrm commented on cmd/agent/internal/config.go
> +package internal
Вообще я бы чуть-чуть пересмотрел структуру проекта и сделал бы примерно так:
cmd:
   agent:
      main.go
   server:
      main.go
internal:
    agent:
        все что в internal для агента в cmd
    server:
        все что в internal для server в cmd

2024-11-21 12:58 UTC, edylcrm commented on cmd/agent/internal/data.go
> +func (ms MemStorage) GetGauge(key string) (gauge, bool) {
Здесь все таки можно сделать сигнатуру функции как `GetGauge(key string) (gauge, error)` в дальнейшем будет проще сделать общий интерфейс когда добавиться psql

2024-11-21 12:58 UTC, edylcrm commented on cmd/agent/internal/data.go
> +func (ms MemStorage) GetCounter(key string) (counter, bool) {
И здесь

2024-11-21 12:58 UTC, edylcrm commented on cmd/agent/internal/send_data_counter.go
> +		for name, value := range Data.MetricsCounter {
Я бы все таки унес mutex туда где структура Data и сделал какой-нибудь метод GetMetricsCounter в котором уже использовал мьютекс и возвращал копию map. 
А здесь и выше в методе убрал бы мьютекс. Вообще лучше всегда хранить мьютекс там же где и данные которые он блокирует. А здесь получается два отдельных мьютекса для двух отдельных методов, они могут работать параллельно и по факту смысла в них особого нет

2024-11-21 12:58 UTC, edylcrm commented on cmd/agent/internal/send_data_gauge.go
> +	mutex.Lock()
Здесь тоже самое

2024-11-21 12:58 UTC, edylcrm commented on cmd/agent/internal/send_data_gauge.go
> +	defer mutex.Unlock()
И здесь

2024-11-21 12:58 UTC, edylcrm commented on cmd/agent/internal/update_data.go
> +	mutex.Lock()
И здесь

2024-11-24 11:01 UTC, UsachevDmitry commented on cmd/agent/internal/config.go
> +package internal
Поправил

2024-11-24 14:04 UTC, UsachevDmitry commented on cmd/agent/internal/send_data_counter.go
> +		for name, value := range Data.MetricsCounter {
Поправил

2024-11-24 14:04 UTC, UsachevDmitry commented on cmd/agent/internal/send_data_gauge.go
> +	mutex.Lock()
Поправил

2024-11-24 14:04 UTC, UsachevDmitry commented on cmd/agent/internal/send_data_gauge.go
> +	defer mutex.Unlock()
Поправил

2024-11-24 14:04 UTC, UsachevDmitry commented on cmd/agent/internal/update_data.go
> +	mutex.Lock()
Поправил

2024-11-24 16:31 UTC, UsachevDmitry commented on cmd/agent/internal/data.go
> +func (ms MemStorage) GetGauge(key string) (gauge, bool) {
Не уверен что правильно понял как сделать сигнатуру функции. Но попробовал.

2024-11-24 16:31 UTC, UsachevDmitry commented on cmd/agent/internal/data.go
> +func (ms MemStorage) GetCounter(key string) (counter, bool) {
Не уверен что правильно понял как сделать сигнатуру функции. Но попробовал.

2024-11-25 09:33 UTC, edylcrm requested changes

2024-11-25 09:33 UTC, edylcrm commented on cmd/server/main.go
> +	var wg sync.WaitGroup
Точно нужен? Вижу, что используется wg.Add(1) и wg.Done(), но не вижу wg.Wait()

2024-11-25 09:33 UTC, edylcrm commented on internal/agent/data.go
> +	var mutex sync.Mutex
Для каждого отдельного метода создавать отдельный mutex не имеет смысла, это не будет работать. Mutex должен быть один на все потоли (горутины) исполнения, чтобы он работал корректно т.е. должно быть как-то так:
```
type MemStorage struct {
	MetricsGauge   map[string]gauge
	MetricsCounter map[string]counter
        mutex sync.Mutex
}

func (m *MemStorage) GetGauge(key string) (gauge, bool) {
      m.mutex.Lock()
      defer m.mutex.Unlock()
      // и так должно быть для каждого метода т.е. mutex общий для всех потолок и методов
      // ... далее реализация
}
```

2024-11-25 13:55 UTC, UsachevDmitry commented on cmd/server/main.go
> +	var wg sync.WaitGroup
поправил

2024-11-25 13:55 UTC, UsachevDmitry commented on internal/agent/data.go
> +	var mutex sync.Mutex
поправил

2024-11-26 08:25 UTC, edylcrm approved these changes

2024-12-11 17:44 UTC, merged